protPI1/posts/forms.py
import wtforms
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, SelectField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Título', validators=[DataRequired()])
    company = StringField('Empresa', validators=[DataRequired()])
    content = TextAreaField('Descrição', validators=[DataRequired()])
    # post_type = StringField('Tipo de Publicação', validators=[DataRequired()])
    post_type = SelectField('Publicação Tipo', choices=[('vaga', 'Vaga'),('curso','Curso')])
    city = StringField('Cidade', validators=[DataRequired()])
    state = StringField('Estado', validators=[DataRequired()])
    #job_level = StringField('Nível da vaga')
    #course_level = StringField('Nível do curso')
    job_mod = StringField('Tipo da vaga')
    course_mod = StringField('Tipo do curso')
    job_level = SelectField('Nível da vaga', choices=[('','-- Nível da vaga --'),('aprendiz','Aprendiz'),('estagio','Estágio'),('trainee', 'Trainee'),('junior','Junior'),('pleno','Pleno'),('senior','Sênior')])
    course_level = SelectField('Nível do curso', choices=[('','-- Nível do curso --'),('iniciante','Iniciante'),('intermediario','Intermediário'),('avancado', 'Avançado')])
    job_mod = SelectField('Tipo da vaga', choices=[('','-- Tipo da vaga --'),('escritorio','Escritório'),('hibrido','Híbrido'),('homeoffice', 'Home Office')])
    course_mod = SelectField('Tipo do curso', choices=[('','-- Tipo do curso --'),('presencial','Presencial'),('semipresencial','Semipresencial'),('ead', 'EAD')])
    link = StringField('Link')
    submit = SubmitField('Publicar!')

protPI1/main/routes.py
from flask import render_template, request, Blueprint
from protPI1.models import Post


main = Blueprint('main', __name__)


# Página Principal
@main.route("/")
@main.route("/home")
def home():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.data_post.desc()).paginate(page=page, per_page=5)
    return render_template('home.html', posts=posts)


@main.route("/vagas")
def vagas():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.filter_by(tipo_post = 'vaga').order_by(Post.data_post.desc()).paginate(page=page, per_page=5)
    return render_template('home.html', posts=posts)


@main.route("/cursos")
def cursos():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.filter_by(tipo_post = 'curso').order_by(Post.data_post.desc()).paginate(page=page, per_page=5)
    return render_template('home.html', posts=posts)


# Página dos Contatinhos, do Quem Somos, do que é o projeto
@main.route("/about")
def about():
    return render_template('about.html', title='Sobre nós')

protPI1/posts/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flask_login import current_user, login_required
from protPI1 import db
from protPI1.models import Post
from protPI1.posts.forms import PostForm


posts = Blueprint('posts', __name__)


# Publicações (CRUD)
# CREATE (Criar nova publicação)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(titulo=form.title.data, empresa=form.company.data, descricao=form.content.data,
                    author=current_user, tipo_post=form.post_type.data, cidade=form.city.data, estado=form.state.data,
                    nivel_vaga=form.job_level.data, nivel_curso=form.course_level.data, mod_vaga=form.job_mod.data,
                    mod_curso=form.course_mod.data, link=form.link.data)
        db.session.add(post)
        db.session.commit()
        flash('Publicado com sucesso!', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='Nova Publicação', form=form, legend='Nova Publicação')


# Abrir página do posts selecionado
@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.titulo, post=post)


# Atualizar posts
@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        '''titulo = form.title.data, empresa = form.company.data, descricao = form.content.data,
        author = current_user, tipo_post = form.post_type.data, cidade = form.city.data, estado = form.state.data,
        nivel_vaga = form.job_level.data, nivel_curso = form.course_level.data, mod_vaga = form.job_mod.data,
        mod_curso = form.course_mod.data, link = form.link.data'''
        post.titulo = form.title.data
        post.empresa = form.company.data
        post.descricao = form.content.data
        post.tipo_post = form.post_type.data
        post.cidade = form.city.data
        post.estado = form.state.data
        post.nivel_vaga = form.job_level.data
        post.nivel_curso = form.course_level.data
        post.mod_vaga = form.job_mod.data
        post.mod_curso = form.course_mod.data
        post.link = form.link.data
        db.session.commit()
        flash('Publicação atualizada!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.titulo
        form.company.data = post.empresa
        form.content.data = post.descricao
        form.post_type.data = post.tipo_post
        form.city.data = post.cidade
        form.state.data = post.estado
        form.job_level.data = post.nivel_vaga
        form.course_level.data = post.nivel_curso
        form.job_mod.data = post.mod_vaga
        form.course_mod.data = post.mod_curso
        form.link.data = post.link
    return render_template('create_post.html', title='Atualizar Publicação', form=form, legend='Atualizar Publicação')


# Deletar Post
@posts.route("/posts/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Publicação removida!', 'success')
    return redirect(url_for('main.home'))

protPI1/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from protPI1 import db, bcrypt
from protPI1.models import User, Post
from protPI1.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from protPI1.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)

#Registrar Usuário (Provavelmente será retirado do principal)
@users.route("/register", methods=['GET', 'POST'])
@login_required
def register():
    # if current_user.is_authenticated:
    #     return redirect(url_for('users.register'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, nome=form.first_name.data, sobrenome=form.last_name.data, email=form.email.data, senha=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('A conta foi criada! O novo usuário já pode logar!', 'success')
        return redirect(url_for('users.register'))
    return render_template('register.html', title='Registrar', form=form)


# Página de Login (Admin only)
@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and bcrypt.check_password_hash(user.senha, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login inválido. Favor checar username e senha!', 'danger')
    return render_template('login.html', title='Login', form=form)


# Dar logout
@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


# Atualizar Dados do Usuário
@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.imgfile = picture_file
        current_user.username = form.username.data
        current_user.nome = form.first_name.data
        current_user.sobrenome = form.last_name.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Perfil atualizado!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.first_name.data = current_user.nome
        form.last_name.data = current_user.sobrenome
        form.email.data = current_user.email
    image_file = url_for('static', filename='img/' + current_user.imgfile)
    return render_template('account.html', title='Perfil', image_file=image_file, form=form)


# Página do autor e seus posts   (externos)
@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(Post.data_post.desc()).paginate(page=page, per_page=5)
    return render_template('user_posts.html', title=f'Publicações de {user.nome}', posts=posts, user=user)


# Redefinir senha  1 - email
@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
     if current_user.is_authenticated:
        return redirect(url_for('main.home'))
     form = RequestResetForm()
     if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('Um email foi enviado com instruções para redefinir sua senha.', 'info')
        return redirect(url_for('users.login'))
     return render_template('reset_request.html', title='Redefinindo senha', form=form)


# Redefinir senha 2 - senha
@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
     if current_user.is_authenticated:
         return redirect(url_for('main.home'))
     user = User.verify_reset_token(token)
     if user is None:
         flash('Este é um token inválido ou expirado', 'warning')
         return redirect(url_for('users.reset_request'))
     form = ResetPasswordForm()
     if form.validate_on_submit():
         hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
         user.senha = hashed_password
         db.session.commit()
         flash('Sua senha foi atualizada! Agora você está apto para logar!', 'success')
         return redirect(url_for('users.login'))
     return render_template('reset_token.html', title='Redefinindo senha', form=form)

protPI1/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <article class="media content-section">
        <div class="media-body">
            <div class="article-metadata">
                <h2>Quem somos?</h2>
            </div>
            <p class="article-content">
                Nós somos um grupo de alunos da Univesp - Pólo Santos! =D
            </p>
        </div>
    </article>
{% endblock content %}

protPI1/templates/account.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ image_file }}">
        <div class="media-body">
          <h2 class="account-heading">{{ current_user.nome }} {{ current_user.sobrenome }}</h2>
          <p class="text-secondary">{{ current_user.username }}</br>{{current_user.email}}</p>
        </div>
      </div>

        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Perfil</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.first_name.label(class="form-control-label") }}

                    {% if form.first_name.errors %}
                        {{ form.first_name(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.first_name.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.first_name(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.last_name.label(class="form-control-label") }}

                    {% if form.last_name.errors %}
                        {{ form.last_name(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.last_name.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.last_name(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.picture.label() }}
                    {{ form.picture(class="form-control-file") }}
                    {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                            <span class="text-danger">{{ error }}</span></br>
                        {% endfor %}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>


    </div>
{% endblock content %}

protPI1/templates/home.html
{% extends "layout.html" %}
{% block content %}
    {% for post in posts.items %}
        <article class="media content-section {{ post.tipo_post }}">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='img/' + post.author.imgfile) }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.nome }}</a>
              <small class="text-muted">{{ post.data_post.strftime("%d/%m/%Y - %H:%M") }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.titulo }}</a></h2>
            <small class="article-content">{{ post.empresa }} - </small>
            <small class="article-content">{{ post.cidade }} / </small>
            <small class="article-content">{{ post.estado }}</small>
            <p class="article-content">{{ post.descricao }}
              <small class="article-content"><a class="" target="_blank" href="{{ post.link }}">{{ post.link }}</a></small>
            </p>
                {% if post.tipo_post == 'vaga' %}
                      <span class="badge bg-steel">{{ post.tipo_post }}</span>
                      <span class="badge bg-steel">{{ post.nivel_vaga }}</span>
                      <span class="badge bg-steel">{{ post.mod_vaga }}</span>
                {% else %}
                      <span class="badge bg-steel">{{ post.tipo_post }}</span>
                      <span class="badge bg-steel">{{ post.nivel_vaga }}</span>
                      <span class="badge bg-steel">{{ post.mod_vaga }}</span>
                {% endif %}
          </div>
        </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
{% endblock content %}

protPI1/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>Webmural - {{ title }}</title>
    {% else %}
        <title>Webmural</title>
    {% endif %}

</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">Webmural</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
              <a class="nav-item nav-link" href="{{ url_for('main.vagas') }}">Vagas</a>
              <a class="nav-item nav-link" href="{{ url_for('main.cursos') }}">Cursos</a>
              <a class="nav-item nav-link" href="{{ url_for('main.about') }}">Quem somos?</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">Publicar</a>
                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Registrar</a>
                <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Perfil</a>
                <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
              {% else %}
              <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>

              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row justify-content-md-center">
        <div class="col-md-7">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>

      </div>
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

protPI1/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.csrf_token() }}
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Login</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}
                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2">
                    <a href="{{ url_for('users.reset_request') }}">Esqueceu a senha?</a>
                </small>
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Seja bem-vindo! {# Conta nova?<a class="ml-2" href="{{ url_for('users.register') }}">Registre-se</a> #}
        </small>
    </div>
{% endblock content %}

protPI1/templates/post.html
{% extends "layout.html" %}
{% block content %}
  <article class="media content-section">
    <img class="rounded-circle article-img" src="{{ url_for('static', filename='img/' + post.author.imgfile) }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.nome }}</a>
        <small class="text-muted">{{ post.data_post.strftime("%d/%m/%Y - %H:%M") }}</small>
        {% if post.author == current_user %}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Atualizar</a>
            <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Remover </button>
          </div>
        {% endif %}
      </div>
      <h2 class="article-title">{{ post.titulo }}</h2>
      <small class="article-content">{{ post.empresa }} - </small>
      <small class="article-content">{{ post.cidade }} / </small>
      <small class="article-content">{{ post.estado }}</small>
            <p class="article-content">{{ post.descricao }}
              <small class="article-content"><a class="" target="_blank" href="{{ post.link }}">{{ post.link }}</a></small>
            </p>
                {% if post.tipo_post == 'vaga' %}
                      <span class="badge bg-steel">{{ post.tipo_post }}</span>
                      <span class="badge bg-steel">{{ post.nivel_vaga }}</span>
                      <span class="badge bg-steel">{{ post.mod_vaga }}</span>
                {% else %}
                      <span class="badge bg-steel">{{ post.tipo_post }}</span>
                      <span class="badge bg-steel">{{ post.nivel_vaga }}</span>
                      <span class="badge bg-steel">{{ post.mod_vaga }}</span>
                {% endif %}
    </div>
  </article>
  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Remover Publicação?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>Você tem certeza disso?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">NÃO</button>
          <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="SIM">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

protPI1/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Redefinir Senha</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

protPI1/templates/user_posts.html
{% extends "layout.html" %}
{% block content %}
    <article class="media content-section">
        <div class="media-body">
            <h2 class="article-title" >Publicações de {{ user.nome }} {{ user.sobrenome }}: {{ posts.total }}</h2>
        </div>
    </article>

    {% for post in posts.items %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='img/' + post.author.imgfile) }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.nome }}</a>
              <small class="text-muted">{{ post.data_post.strftime("%d/%m/%Y - %H:%M") }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.titulo }}</a></h2>
            <small class="article-content">{{ post.empresa }}</small>
            <small class="article-content">{{ post.cidade }} / </small>
            <small class="article-content">{{ post.estado }}</small>
            <p class="article-content">{{ post.descricao }}
              <small class="article-content"><a class="" target="_blank" href="{{ post.link }}">{{ post.link }}</a></small>
            </p>
                {% if post.tipo_post == 'vaga' %}
                      <span class="badge bg-steel">{{ post.tipo_post }}</span>
                      <span class="badge bg-steel">{{ post.nivel_vaga }}</span>
                      <span class="badge bg-steel">{{ post.mod_vaga }}</span>
                {% else %}
                      <span class="badge bg-steel">{{ post.tipo_post }}</span>
                      <span class="badge bg-steel">{{ post.nivel_vaga }}</span>
                      <span class="badge bg-steel">{{ post.mod_vaga }}</span>
                {% endif %}
          </div>
        </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
{% endblock content %}